name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "1 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
      - name: Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@main
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_fortune: yes
